names:
- Car
- Van
- Truck
- Pedestrian
- Person_sitting
- Cyclist
- Tram
- Misc
nc: 8
path: /Users/tanishyadav/Documents/machine-learning-project/data/kitti
test: testing/image_2
train: training/image_2
val: training/image_2
